# -*- coding: utf-8 -*-
"""test_load

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Gn32pZLiJUEybYDVKbVT1QiqwcimOX0
"""

import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from utils.transform import get_fashion
from utils.load import load_to_csv, set_with_dataframe, worksheet
import gspread
from utils.transform import get_fashion
from gspread_dataframe import set_with_dataframe, get_as_dataframe
from oauth2client.service_account import ServiceAccountCredentials

def test_csv_saving():
    fashion_df = get_fashion()
    output_path = "test_output.csv"

    success = load_to_csv(fashion_df, output_path)
    assert success, "Gagal menyimpan ke CSV"
    assert os.path.exists(output_path), "File CSV tidak ditemukan"
    print("Test CSV: BERHASIL")

if __name__ == "__main__":
    test_csv_saving()

def test_google_sheet_upload():
    scope = [
        "https://spreadsheets.google.com/feeds",
        "https://www.googleapis.com/auth/drive"
    ]
    creds = ServiceAccountCredentials.from_json_keyfile_name("products.json", scope)
    client = gspread.authorize(creds)

    spreadsheet_name = "products"
    sheet_title = "Data Fashion"

    spreadsheet = client.open(spreadsheet_name)
    try:
        worksheet = spreadsheet.worksheet(sheet_title)
    except:
        worksheet = spreadsheet.add_worksheet(title=sheet_title, rows="1000", cols="50")

    fashion_df = get_fashion()
    worksheet.clear()
    set_with_dataframe(worksheet, fashion_df)

    # Test baca kembali
    df_from_sheet = get_as_dataframe(worksheet).dropna(how="all")
    assert not df_from_sheet.empty, "Data dari Google Sheet kosong"
    print("Test Spreadsheet: BERHASIL")

if __name__ == "__main__":
    test_google_sheet_upload()
