# -*- coding: utf-8 -*-
"""transform_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOWWTZLMP6fgwR17BSMokquZw7daw1zz
"""

import pytest
import pandas as pd
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from utils.transform import transform_data

@pytest.fixture
def data_dummy():
    return pd.DataFrame({
        'title': ['Produk A', 'Produk Tidak Dikenal', 'Produk B'],
        'price': ['$19.99', 'Price Unavailable', '€25.00'],
        'rating': ['4.5', 'Invalid Rating / 5', '3.8'],
        'colors': ['5', 'N/A', '3'],
        'size': ['M', 'L', 'XL'],
        'gender': ['Pria', 'Wanita', 'Unisex'],
        'timestamp': ['2024-01-01', '2024-01-02', '2024-01-03']
    })

def test_konversi_harga_ke_rupiah(data_dummy):
    hasil = transform_data(data_dummy.copy(), exchange_rate=16000)

    assert 'price_in_usd' in hasil.columns
    assert 'price_in_rupiah' in hasil.columns

    usd = hasil.loc[0, 'price_in_usd']
    idr = hasil.loc[0, 'price_in_rupiah']
    assert usd == 19.99
    assert idr == int(19.99 * 16000)

def test_penanganan_format_harga_tidak_valid(data_dummy):
    hasil = transform_data(data_dummy.copy(), exchange_rate=16000)

    # Harus diubah ke 0 jika tidak bisa dikonversi
    assert hasil.loc[1, 'price_in_usd'] == 0
    assert hasil.loc[1, 'price_in_rupiah'] == 0

def test_konversi_harga_mata_uang_lain(data_dummy):
    hasil = transform_data(data_dummy.copy(), exchange_rate=16000)

    # Euro tetap dikonversi angka saja
    assert hasil.loc[2, 'price_in_usd'] == 25.00
    assert hasil.loc[2, 'price_in_rupiah'] == int(25.00 * 16000)
