# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZ-NHoorO3SToZySI7s1WXf0olyAt9XX
"""

import pandas as pd
from utils.extract import scrape_fashion
from utils.transform import get_fashion
from utils.load import load_to_csv, set_with_dataframe, worksheet

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

def run_etl():
    print("Memulai proses ETL")
        # -------------------- EXTRACT --------------------
    print("Scraping dari website...")
    data = scrape_fashion(start_page=1, max_pages=50, delay=1)
    if not data:
        print("Tidak ada data yang berhasil diambil.")
        return

    df = pd.DataFrame(data)
    print(f"Jumlah data awal (raw): {len(df)}")

    # -------------------- TRANSFORM --------------------
    print("Mengambil hasil transformasi dari transform.py...")
    fashion = get_fashion()

    print(f"Jumlah akhir hasil transform.py: {len(fashion)}")

    print("\nContoh hasil transformasi:")
    print(fashion.head())

    print("\nTipe data kolom:")
    fashion.info()

    # -------------------- LOAD --------------------
    print("\nMenyimpan ke CSV dan Google Spreadsheet...")
    if load_to_csv(fashion, "products.csv"):
        print("File CSV berhasil disimpan.")

    worksheet.clear()
    set_with_dataframe(worksheet, fashion)
    print("Data berhasil disimpan ke Google Spreadsheet.")

if __name__ == "__main__":
    run_etl()